services:

    embaNET-intranet-portal:

        container_name: embaNET-intranet-portal 

        image: softwareshinobi/embanet-intranet-portal 

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "80:80"
